exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-Modernist

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/vitaliy-shkolnik"
  
title: Vitaliy Shkolnik
description: Projects
